classDiagram

class Scooter {
    +string station
    +string user
    +number serial
    +number charge
    +bool isBroken
    +book dock
    +rent()
    +docked(station)
    +recharge()
    +requestRepair()
}

class User {
    +string username
    +string password
    +number age
}

