sequenceDiagram
    Customer ->> Book: Add to basket
    activate Book
    Book ->> Basket: Added
    activate Basket
    Basket -->> Customer: Display total
    deactivate Basket
    
    alt cancels purchase
        Customer ->> Basket: Cancel
        Basket ->> Book: Remove
        Basket -->> Customer: Confirm
        deactivate Book
    else complete purchase
        activate Book
        Customer ->> Basket: Payment details
        activate Basket
        Basket -->> Customer: Confirm
        deactivate Basket
        Book -->> Customer: Ship
        deactivate Book
    end