sequenceDiagram
    loop For all scooters
        Scooter ->> ScooterApp : Add scooter
    end

    User ->> ScooterApp: Register
    alt already registered
        ScooterApp -->> User: Log 'already registered'
    else not already registered
        alt older than seventeen
            ScooterApp --> User: Complete user account
            ScooterApp -->> User: Log 'now registered'
        else younger than seventeen
            ScooterApp -->> User: Log 'too young'
        end
    end
    
    User ->> ScooterApp: Log in
    alt login matches 
        ScooterApp -->> User: Log 'correct'
        User ->> ScooterApp: Rent request
        alt scooter broken
        ScooterApp -->> User: Log 'request repair'
            User ->> Scooter: Request repair
            Scooter ->> ScooterApp: Remove scooter
            User ->> Scooter: Dock scooter
                alt no station
                    Scooter -->> User: Log 'please dock'
                else at station
                    ScooterApp --> Scooter: Scooter repair time
                    activate Scooter
                    ScooterApp ->> Scooter: Update working status
                    Scooter ->> ScooterApp: Add scooter
                end
        else scooter working
            alt charge > 20
                ScooterApp -->> User: Log 'enjoy ride'
            else charge <= 20
                ScooterApp -->> User: Log 'please charge'
                User -->> Scooter: Recharge scooter
            end
            Scooter ->> ScooterApp: Rent scooter
            User ->> ScooterApp: Return scooter
            User ->> Scooter: Dock scooter
        end
    else login does not match
        ScooterApp -->> User: Log 'incorrect'
    end